package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Booking implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.book_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer programmeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.book_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Date bookDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.book_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column booking.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.book_id
     *
     * @return the value of booking.book_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.book_id
     *
     * @param bookId the value for booking.book_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.cust_id
     *
     * @return the value of booking.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.cust_id
     *
     * @param custId the value for booking.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.ent_id
     *
     * @return the value of booking.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.ent_id
     *
     * @param entId the value for booking.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntId(Integer entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.programme_id
     *
     * @return the value of booking.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getProgrammeId() {
        return programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.programme_id
     *
     * @param programmeId the value for booking.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeId(Integer programmeId) {
        this.programmeId = programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.book_date
     *
     * @return the value of booking.book_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Date getBookDate() {
        return bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.book_date
     *
     * @param bookDate the value for booking.book_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.book_status
     *
     * @return the value of booking.book_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.book_status
     *
     * @param bookStatus the value for booking.book_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.other1
     *
     * @return the value of booking.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.other1
     *
     * @param other1 the value for booking.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column booking.other2
     *
     * @return the value of booking.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column booking.other2
     *
     * @param other2 the value for booking.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookId=").append(bookId);
        sb.append(", custId=").append(custId);
        sb.append(", entId=").append(entId);
        sb.append(", programmeId=").append(programmeId);
        sb.append(", bookDate=").append(bookDate);
        sb.append(", bookStatus=").append(bookStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}