package com.aistar.pojo;

import java.io.Serializable;

public class Calculator implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.calculator_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer calculatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.homesize
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer homesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.home_room
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String homeRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.home_parlour
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String homeParlour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.home_kitchen
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String homeKitchen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.home_toilet
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String homeToilet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.home_balcony
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String homeBalcony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.material_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer materialCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.labour_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer labourCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.design_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer designCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.quality_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer qualityCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.calculator_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer calculatorStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calculator.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.calculator_id
     *
     * @return the value of calculator.calculator_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCalculatorId() {
        return calculatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.calculator_id
     *
     * @param calculatorId the value for calculator.calculator_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCalculatorId(Integer calculatorId) {
        this.calculatorId = calculatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.cust_id
     *
     * @return the value of calculator.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.cust_id
     *
     * @param custId the value for calculator.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.homesize
     *
     * @return the value of calculator.homesize
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getHomesize() {
        return homesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.homesize
     *
     * @param homesize the value for calculator.homesize
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomesize(Integer homesize) {
        this.homesize = homesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.home_room
     *
     * @return the value of calculator.home_room
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getHomeRoom() {
        return homeRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.home_room
     *
     * @param homeRoom the value for calculator.home_room
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomeRoom(String homeRoom) {
        this.homeRoom = homeRoom == null ? null : homeRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.home_parlour
     *
     * @return the value of calculator.home_parlour
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getHomeParlour() {
        return homeParlour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.home_parlour
     *
     * @param homeParlour the value for calculator.home_parlour
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomeParlour(String homeParlour) {
        this.homeParlour = homeParlour == null ? null : homeParlour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.home_kitchen
     *
     * @return the value of calculator.home_kitchen
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getHomeKitchen() {
        return homeKitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.home_kitchen
     *
     * @param homeKitchen the value for calculator.home_kitchen
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomeKitchen(String homeKitchen) {
        this.homeKitchen = homeKitchen == null ? null : homeKitchen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.home_toilet
     *
     * @return the value of calculator.home_toilet
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getHomeToilet() {
        return homeToilet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.home_toilet
     *
     * @param homeToilet the value for calculator.home_toilet
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomeToilet(String homeToilet) {
        this.homeToilet = homeToilet == null ? null : homeToilet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.home_balcony
     *
     * @return the value of calculator.home_balcony
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getHomeBalcony() {
        return homeBalcony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.home_balcony
     *
     * @param homeBalcony the value for calculator.home_balcony
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setHomeBalcony(String homeBalcony) {
        this.homeBalcony = homeBalcony == null ? null : homeBalcony.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.material_cost
     *
     * @return the value of calculator.material_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getMaterialCost() {
        return materialCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.material_cost
     *
     * @param materialCost the value for calculator.material_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setMaterialCost(Integer materialCost) {
        this.materialCost = materialCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.labour_cost
     *
     * @return the value of calculator.labour_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getLabourCost() {
        return labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.labour_cost
     *
     * @param labourCost the value for calculator.labour_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setLabourCost(Integer labourCost) {
        this.labourCost = labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.design_cost
     *
     * @return the value of calculator.design_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDesignCost() {
        return designCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.design_cost
     *
     * @param designCost the value for calculator.design_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignCost(Integer designCost) {
        this.designCost = designCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.quality_cost
     *
     * @return the value of calculator.quality_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getQualityCost() {
        return qualityCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.quality_cost
     *
     * @param qualityCost the value for calculator.quality_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setQualityCost(Integer qualityCost) {
        this.qualityCost = qualityCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.calculator_status
     *
     * @return the value of calculator.calculator_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCalculatorStatus() {
        return calculatorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.calculator_status
     *
     * @param calculatorStatus the value for calculator.calculator_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCalculatorStatus(Integer calculatorStatus) {
        this.calculatorStatus = calculatorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.other1
     *
     * @return the value of calculator.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.other1
     *
     * @param other1 the value for calculator.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calculator.other2
     *
     * @return the value of calculator.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calculator.other2
     *
     * @param other2 the value for calculator.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", calculatorId=").append(calculatorId);
        sb.append(", custId=").append(custId);
        sb.append(", homesize=").append(homesize);
        sb.append(", homeRoom=").append(homeRoom);
        sb.append(", homeParlour=").append(homeParlour);
        sb.append(", homeKitchen=").append(homeKitchen);
        sb.append(", homeToilet=").append(homeToilet);
        sb.append(", homeBalcony=").append(homeBalcony);
        sb.append(", materialCost=").append(materialCost);
        sb.append(", labourCost=").append(labourCost);
        sb.append(", designCost=").append(designCost);
        sb.append(", qualityCost=").append(qualityCost);
        sb.append(", calculatorStatus=").append(calculatorStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}