package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class CalculatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public CalculatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCalculatorIdIsNull() {
            addCriterion("calculator_id is null");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdIsNotNull() {
            addCriterion("calculator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdEqualTo(Integer value) {
            addCriterion("calculator_id =", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdNotEqualTo(Integer value) {
            addCriterion("calculator_id <>", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdGreaterThan(Integer value) {
            addCriterion("calculator_id >", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("calculator_id >=", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdLessThan(Integer value) {
            addCriterion("calculator_id <", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("calculator_id <=", value, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdIn(List<Integer> values) {
            addCriterion("calculator_id in", values, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdNotIn(List<Integer> values) {
            addCriterion("calculator_id not in", values, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdBetween(Integer value1, Integer value2) {
            addCriterion("calculator_id between", value1, value2, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCalculatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("calculator_id not between", value1, value2, "calculatorId");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andHomesizeIsNull() {
            addCriterion("homesize is null");
            return (Criteria) this;
        }

        public Criteria andHomesizeIsNotNull() {
            addCriterion("homesize is not null");
            return (Criteria) this;
        }

        public Criteria andHomesizeEqualTo(Integer value) {
            addCriterion("homesize =", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeNotEqualTo(Integer value) {
            addCriterion("homesize <>", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeGreaterThan(Integer value) {
            addCriterion("homesize >", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("homesize >=", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeLessThan(Integer value) {
            addCriterion("homesize <", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeLessThanOrEqualTo(Integer value) {
            addCriterion("homesize <=", value, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeIn(List<Integer> values) {
            addCriterion("homesize in", values, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeNotIn(List<Integer> values) {
            addCriterion("homesize not in", values, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeBetween(Integer value1, Integer value2) {
            addCriterion("homesize between", value1, value2, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomesizeNotBetween(Integer value1, Integer value2) {
            addCriterion("homesize not between", value1, value2, "homesize");
            return (Criteria) this;
        }

        public Criteria andHomeRoomIsNull() {
            addCriterion("home_room is null");
            return (Criteria) this;
        }

        public Criteria andHomeRoomIsNotNull() {
            addCriterion("home_room is not null");
            return (Criteria) this;
        }

        public Criteria andHomeRoomEqualTo(String value) {
            addCriterion("home_room =", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomNotEqualTo(String value) {
            addCriterion("home_room <>", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomGreaterThan(String value) {
            addCriterion("home_room >", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomGreaterThanOrEqualTo(String value) {
            addCriterion("home_room >=", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomLessThan(String value) {
            addCriterion("home_room <", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomLessThanOrEqualTo(String value) {
            addCriterion("home_room <=", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomLike(String value) {
            addCriterion("home_room like", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomNotLike(String value) {
            addCriterion("home_room not like", value, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomIn(List<String> values) {
            addCriterion("home_room in", values, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomNotIn(List<String> values) {
            addCriterion("home_room not in", values, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomBetween(String value1, String value2) {
            addCriterion("home_room between", value1, value2, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeRoomNotBetween(String value1, String value2) {
            addCriterion("home_room not between", value1, value2, "homeRoom");
            return (Criteria) this;
        }

        public Criteria andHomeParlourIsNull() {
            addCriterion("home_parlour is null");
            return (Criteria) this;
        }

        public Criteria andHomeParlourIsNotNull() {
            addCriterion("home_parlour is not null");
            return (Criteria) this;
        }

        public Criteria andHomeParlourEqualTo(String value) {
            addCriterion("home_parlour =", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourNotEqualTo(String value) {
            addCriterion("home_parlour <>", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourGreaterThan(String value) {
            addCriterion("home_parlour >", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourGreaterThanOrEqualTo(String value) {
            addCriterion("home_parlour >=", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourLessThan(String value) {
            addCriterion("home_parlour <", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourLessThanOrEqualTo(String value) {
            addCriterion("home_parlour <=", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourLike(String value) {
            addCriterion("home_parlour like", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourNotLike(String value) {
            addCriterion("home_parlour not like", value, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourIn(List<String> values) {
            addCriterion("home_parlour in", values, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourNotIn(List<String> values) {
            addCriterion("home_parlour not in", values, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourBetween(String value1, String value2) {
            addCriterion("home_parlour between", value1, value2, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeParlourNotBetween(String value1, String value2) {
            addCriterion("home_parlour not between", value1, value2, "homeParlour");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenIsNull() {
            addCriterion("home_kitchen is null");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenIsNotNull() {
            addCriterion("home_kitchen is not null");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenEqualTo(String value) {
            addCriterion("home_kitchen =", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenNotEqualTo(String value) {
            addCriterion("home_kitchen <>", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenGreaterThan(String value) {
            addCriterion("home_kitchen >", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenGreaterThanOrEqualTo(String value) {
            addCriterion("home_kitchen >=", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenLessThan(String value) {
            addCriterion("home_kitchen <", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenLessThanOrEqualTo(String value) {
            addCriterion("home_kitchen <=", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenLike(String value) {
            addCriterion("home_kitchen like", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenNotLike(String value) {
            addCriterion("home_kitchen not like", value, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenIn(List<String> values) {
            addCriterion("home_kitchen in", values, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenNotIn(List<String> values) {
            addCriterion("home_kitchen not in", values, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenBetween(String value1, String value2) {
            addCriterion("home_kitchen between", value1, value2, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeKitchenNotBetween(String value1, String value2) {
            addCriterion("home_kitchen not between", value1, value2, "homeKitchen");
            return (Criteria) this;
        }

        public Criteria andHomeToiletIsNull() {
            addCriterion("home_toilet is null");
            return (Criteria) this;
        }

        public Criteria andHomeToiletIsNotNull() {
            addCriterion("home_toilet is not null");
            return (Criteria) this;
        }

        public Criteria andHomeToiletEqualTo(String value) {
            addCriterion("home_toilet =", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletNotEqualTo(String value) {
            addCriterion("home_toilet <>", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletGreaterThan(String value) {
            addCriterion("home_toilet >", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletGreaterThanOrEqualTo(String value) {
            addCriterion("home_toilet >=", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletLessThan(String value) {
            addCriterion("home_toilet <", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletLessThanOrEqualTo(String value) {
            addCriterion("home_toilet <=", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletLike(String value) {
            addCriterion("home_toilet like", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletNotLike(String value) {
            addCriterion("home_toilet not like", value, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletIn(List<String> values) {
            addCriterion("home_toilet in", values, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletNotIn(List<String> values) {
            addCriterion("home_toilet not in", values, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletBetween(String value1, String value2) {
            addCriterion("home_toilet between", value1, value2, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeToiletNotBetween(String value1, String value2) {
            addCriterion("home_toilet not between", value1, value2, "homeToilet");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyIsNull() {
            addCriterion("home_balcony is null");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyIsNotNull() {
            addCriterion("home_balcony is not null");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyEqualTo(String value) {
            addCriterion("home_balcony =", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyNotEqualTo(String value) {
            addCriterion("home_balcony <>", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyGreaterThan(String value) {
            addCriterion("home_balcony >", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyGreaterThanOrEqualTo(String value) {
            addCriterion("home_balcony >=", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyLessThan(String value) {
            addCriterion("home_balcony <", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyLessThanOrEqualTo(String value) {
            addCriterion("home_balcony <=", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyLike(String value) {
            addCriterion("home_balcony like", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyNotLike(String value) {
            addCriterion("home_balcony not like", value, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyIn(List<String> values) {
            addCriterion("home_balcony in", values, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyNotIn(List<String> values) {
            addCriterion("home_balcony not in", values, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyBetween(String value1, String value2) {
            addCriterion("home_balcony between", value1, value2, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andHomeBalconyNotBetween(String value1, String value2) {
            addCriterion("home_balcony not between", value1, value2, "homeBalcony");
            return (Criteria) this;
        }

        public Criteria andMaterialCostIsNull() {
            addCriterion("material_cost is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCostIsNotNull() {
            addCriterion("material_cost is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCostEqualTo(Integer value) {
            addCriterion("material_cost =", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostNotEqualTo(Integer value) {
            addCriterion("material_cost <>", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostGreaterThan(Integer value) {
            addCriterion("material_cost >", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_cost >=", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostLessThan(Integer value) {
            addCriterion("material_cost <", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostLessThanOrEqualTo(Integer value) {
            addCriterion("material_cost <=", value, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostIn(List<Integer> values) {
            addCriterion("material_cost in", values, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostNotIn(List<Integer> values) {
            addCriterion("material_cost not in", values, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostBetween(Integer value1, Integer value2) {
            addCriterion("material_cost between", value1, value2, "materialCost");
            return (Criteria) this;
        }

        public Criteria andMaterialCostNotBetween(Integer value1, Integer value2) {
            addCriterion("material_cost not between", value1, value2, "materialCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostIsNull() {
            addCriterion("labour_cost is null");
            return (Criteria) this;
        }

        public Criteria andLabourCostIsNotNull() {
            addCriterion("labour_cost is not null");
            return (Criteria) this;
        }

        public Criteria andLabourCostEqualTo(Integer value) {
            addCriterion("labour_cost =", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostNotEqualTo(Integer value) {
            addCriterion("labour_cost <>", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostGreaterThan(Integer value) {
            addCriterion("labour_cost >", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostGreaterThanOrEqualTo(Integer value) {
            addCriterion("labour_cost >=", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostLessThan(Integer value) {
            addCriterion("labour_cost <", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostLessThanOrEqualTo(Integer value) {
            addCriterion("labour_cost <=", value, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostIn(List<Integer> values) {
            addCriterion("labour_cost in", values, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostNotIn(List<Integer> values) {
            addCriterion("labour_cost not in", values, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostBetween(Integer value1, Integer value2) {
            addCriterion("labour_cost between", value1, value2, "labourCost");
            return (Criteria) this;
        }

        public Criteria andLabourCostNotBetween(Integer value1, Integer value2) {
            addCriterion("labour_cost not between", value1, value2, "labourCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostIsNull() {
            addCriterion("design_cost is null");
            return (Criteria) this;
        }

        public Criteria andDesignCostIsNotNull() {
            addCriterion("design_cost is not null");
            return (Criteria) this;
        }

        public Criteria andDesignCostEqualTo(Integer value) {
            addCriterion("design_cost =", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostNotEqualTo(Integer value) {
            addCriterion("design_cost <>", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostGreaterThan(Integer value) {
            addCriterion("design_cost >", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostGreaterThanOrEqualTo(Integer value) {
            addCriterion("design_cost >=", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostLessThan(Integer value) {
            addCriterion("design_cost <", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostLessThanOrEqualTo(Integer value) {
            addCriterion("design_cost <=", value, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostIn(List<Integer> values) {
            addCriterion("design_cost in", values, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostNotIn(List<Integer> values) {
            addCriterion("design_cost not in", values, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostBetween(Integer value1, Integer value2) {
            addCriterion("design_cost between", value1, value2, "designCost");
            return (Criteria) this;
        }

        public Criteria andDesignCostNotBetween(Integer value1, Integer value2) {
            addCriterion("design_cost not between", value1, value2, "designCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostIsNull() {
            addCriterion("quality_cost is null");
            return (Criteria) this;
        }

        public Criteria andQualityCostIsNotNull() {
            addCriterion("quality_cost is not null");
            return (Criteria) this;
        }

        public Criteria andQualityCostEqualTo(Integer value) {
            addCriterion("quality_cost =", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostNotEqualTo(Integer value) {
            addCriterion("quality_cost <>", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostGreaterThan(Integer value) {
            addCriterion("quality_cost >", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostGreaterThanOrEqualTo(Integer value) {
            addCriterion("quality_cost >=", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostLessThan(Integer value) {
            addCriterion("quality_cost <", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostLessThanOrEqualTo(Integer value) {
            addCriterion("quality_cost <=", value, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostIn(List<Integer> values) {
            addCriterion("quality_cost in", values, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostNotIn(List<Integer> values) {
            addCriterion("quality_cost not in", values, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostBetween(Integer value1, Integer value2) {
            addCriterion("quality_cost between", value1, value2, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andQualityCostNotBetween(Integer value1, Integer value2) {
            addCriterion("quality_cost not between", value1, value2, "qualityCost");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusIsNull() {
            addCriterion("calculator_status is null");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusIsNotNull() {
            addCriterion("calculator_status is not null");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusEqualTo(Integer value) {
            addCriterion("calculator_status =", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusNotEqualTo(Integer value) {
            addCriterion("calculator_status <>", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusGreaterThan(Integer value) {
            addCriterion("calculator_status >", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("calculator_status >=", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusLessThan(Integer value) {
            addCriterion("calculator_status <", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusLessThanOrEqualTo(Integer value) {
            addCriterion("calculator_status <=", value, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusIn(List<Integer> values) {
            addCriterion("calculator_status in", values, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusNotIn(List<Integer> values) {
            addCriterion("calculator_status not in", values, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusBetween(Integer value1, Integer value2) {
            addCriterion("calculator_status between", value1, value2, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andCalculatorStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("calculator_status not between", value1, value2, "calculatorStatus");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calculator
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}