package com.aistar.pojo;

import java.io.Serializable;

public class CollectionsDiary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.collection_diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer collectionDiaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer collectionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections_diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.collection_diary_id
     *
     * @return the value of collections_diary.collection_diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCollectionDiaryId() {
        return collectionDiaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.collection_diary_id
     *
     * @param collectionDiaryId the value for collections_diary.collection_diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectionDiaryId(Integer collectionDiaryId) {
        this.collectionDiaryId = collectionDiaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.cust_id
     *
     * @return the value of collections_diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.cust_id
     *
     * @param custId the value for collections_diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.diary_id
     *
     * @return the value of collections_diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.diary_id
     *
     * @param diaryId the value for collections_diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryId(Integer diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.collection_status
     *
     * @return the value of collections_diary.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCollectionStatus() {
        return collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.collection_status
     *
     * @param collectionStatus the value for collections_diary.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectionStatus(Integer collectionStatus) {
        this.collectionStatus = collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.other1
     *
     * @return the value of collections_diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.other1
     *
     * @param other1 the value for collections_diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections_diary.other2
     *
     * @return the value of collections_diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections_diary.other2
     *
     * @param other2 the value for collections_diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectionDiaryId=").append(collectionDiaryId);
        sb.append(", custId=").append(custId);
        sb.append(", diaryId=").append(diaryId);
        sb.append(", collectionStatus=").append(collectionStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}