package com.aistar.pojo;

import java.io.Serializable;

public class Collections implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.collection_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer collectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer programmeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer collectionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collections.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.collection_id
     *
     * @return the value of collections.collection_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.collection_id
     *
     * @param collectionId the value for collections.collection_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.cust_id
     *
     * @return the value of collections.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.cust_id
     *
     * @param custId the value for collections.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.programme_id
     *
     * @return the value of collections.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getProgrammeId() {
        return programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.programme_id
     *
     * @param programmeId the value for collections.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeId(Integer programmeId) {
        this.programmeId = programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.collection_status
     *
     * @return the value of collections.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCollectionStatus() {
        return collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.collection_status
     *
     * @param collectionStatus the value for collections.collection_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectionStatus(Integer collectionStatus) {
        this.collectionStatus = collectionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.other1
     *
     * @return the value of collections.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.other1
     *
     * @param other1 the value for collections.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collections.other2
     *
     * @return the value of collections.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collections.other2
     *
     * @param other2 the value for collections.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectionId=").append(collectionId);
        sb.append(", custId=").append(custId);
        sb.append(", programmeId=").append(programmeId);
        sb.append(", collectionStatus=").append(collectionStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}