package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Comments implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer commentsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.reporter_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer reporterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.reporter_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String reporterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.repor_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String reporContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.respondent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer respondentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.respondent_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String respondentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer commentsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Date commentsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_id
     *
     * @return the value of comments.comments_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCommentsId() {
        return commentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_id
     *
     * @param commentsId the value for comments.comments_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCommentsId(Integer commentsId) {
        this.commentsId = commentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.reporter_id
     *
     * @return the value of comments.reporter_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getReporterId() {
        return reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.reporter_id
     *
     * @param reporterId the value for comments.reporter_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setReporterId(Integer reporterId) {
        this.reporterId = reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.reporter_name
     *
     * @return the value of comments.reporter_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getReporterName() {
        return reporterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.reporter_name
     *
     * @param reporterName the value for comments.reporter_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setReporterName(String reporterName) {
        this.reporterName = reporterName == null ? null : reporterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.repor_content
     *
     * @return the value of comments.repor_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getReporContent() {
        return reporContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.repor_content
     *
     * @param reporContent the value for comments.repor_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setReporContent(String reporContent) {
        this.reporContent = reporContent == null ? null : reporContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.respondent_id
     *
     * @return the value of comments.respondent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getRespondentId() {
        return respondentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.respondent_id
     *
     * @param respondentId the value for comments.respondent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setRespondentId(Integer respondentId) {
        this.respondentId = respondentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.respondent_content
     *
     * @return the value of comments.respondent_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getRespondentContent() {
        return respondentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.respondent_content
     *
     * @param respondentContent the value for comments.respondent_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setRespondentContent(String respondentContent) {
        this.respondentContent = respondentContent == null ? null : respondentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_status
     *
     * @return the value of comments.comments_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCommentsStatus() {
        return commentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_status
     *
     * @param commentsStatus the value for comments.comments_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCommentsStatus(Integer commentsStatus) {
        this.commentsStatus = commentsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments_date
     *
     * @return the value of comments.comments_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Date getCommentsDate() {
        return commentsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments_date
     *
     * @param commentsDate the value for comments.comments_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCommentsDate(Date commentsDate) {
        this.commentsDate = commentsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.other1
     *
     * @return the value of comments.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.other1
     *
     * @param other1 the value for comments.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.other2
     *
     * @return the value of comments.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.other2
     *
     * @param other2 the value for comments.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentsId=").append(commentsId);
        sb.append(", reporterId=").append(reporterId);
        sb.append(", reporterName=").append(reporterName);
        sb.append(", reporContent=").append(reporContent);
        sb.append(", respondentId=").append(respondentId);
        sb.append(", respondentContent=").append(respondentContent);
        sb.append(", commentsStatus=").append(commentsStatus);
        sb.append(", commentsDate=").append(commentsDate);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}