package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIsNull() {
            addCriterion("cust_nickname is null");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIsNotNull() {
            addCriterion("cust_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andCustNicknameEqualTo(String value) {
            addCriterion("cust_nickname =", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotEqualTo(String value) {
            addCriterion("cust_nickname <>", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameGreaterThan(String value) {
            addCriterion("cust_nickname >", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_nickname >=", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLessThan(String value) {
            addCriterion("cust_nickname <", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLessThanOrEqualTo(String value) {
            addCriterion("cust_nickname <=", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameLike(String value) {
            addCriterion("cust_nickname like", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotLike(String value) {
            addCriterion("cust_nickname not like", value, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameIn(List<String> values) {
            addCriterion("cust_nickname in", values, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotIn(List<String> values) {
            addCriterion("cust_nickname not in", values, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameBetween(String value1, String value2) {
            addCriterion("cust_nickname between", value1, value2, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustNicknameNotBetween(String value1, String value2) {
            addCriterion("cust_nickname not between", value1, value2, "custNickname");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIsNull() {
            addCriterion("cust_password is null");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIsNotNull() {
            addCriterion("cust_password is not null");
            return (Criteria) this;
        }

        public Criteria andCustPasswordEqualTo(String value) {
            addCriterion("cust_password =", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotEqualTo(String value) {
            addCriterion("cust_password <>", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordGreaterThan(String value) {
            addCriterion("cust_password >", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("cust_password >=", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLessThan(String value) {
            addCriterion("cust_password <", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLessThanOrEqualTo(String value) {
            addCriterion("cust_password <=", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordLike(String value) {
            addCriterion("cust_password like", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotLike(String value) {
            addCriterion("cust_password not like", value, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordIn(List<String> values) {
            addCriterion("cust_password in", values, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotIn(List<String> values) {
            addCriterion("cust_password not in", values, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordBetween(String value1, String value2) {
            addCriterion("cust_password between", value1, value2, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustPasswordNotBetween(String value1, String value2) {
            addCriterion("cust_password not between", value1, value2, "custPassword");
            return (Criteria) this;
        }

        public Criteria andCustTelIsNull() {
            addCriterion("cust_tel is null");
            return (Criteria) this;
        }

        public Criteria andCustTelIsNotNull() {
            addCriterion("cust_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCustTelEqualTo(Long value) {
            addCriterion("cust_tel =", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelNotEqualTo(Long value) {
            addCriterion("cust_tel <>", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelGreaterThan(Long value) {
            addCriterion("cust_tel >", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelGreaterThanOrEqualTo(Long value) {
            addCriterion("cust_tel >=", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelLessThan(Long value) {
            addCriterion("cust_tel <", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelLessThanOrEqualTo(Long value) {
            addCriterion("cust_tel <=", value, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelIn(List<Long> values) {
            addCriterion("cust_tel in", values, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelNotIn(List<Long> values) {
            addCriterion("cust_tel not in", values, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelBetween(Long value1, Long value2) {
            addCriterion("cust_tel between", value1, value2, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustTelNotBetween(Long value1, Long value2) {
            addCriterion("cust_tel not between", value1, value2, "custTel");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoIsNull() {
            addCriterion("cust_headphoto is null");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoIsNotNull() {
            addCriterion("cust_headphoto is not null");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoEqualTo(String value) {
            addCriterion("cust_headphoto =", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoNotEqualTo(String value) {
            addCriterion("cust_headphoto <>", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoGreaterThan(String value) {
            addCriterion("cust_headphoto >", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoGreaterThanOrEqualTo(String value) {
            addCriterion("cust_headphoto >=", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoLessThan(String value) {
            addCriterion("cust_headphoto <", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoLessThanOrEqualTo(String value) {
            addCriterion("cust_headphoto <=", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoLike(String value) {
            addCriterion("cust_headphoto like", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoNotLike(String value) {
            addCriterion("cust_headphoto not like", value, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoIn(List<String> values) {
            addCriterion("cust_headphoto in", values, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoNotIn(List<String> values) {
            addCriterion("cust_headphoto not in", values, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoBetween(String value1, String value2) {
            addCriterion("cust_headphoto between", value1, value2, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustHeadphotoNotBetween(String value1, String value2) {
            addCriterion("cust_headphoto not between", value1, value2, "custHeadphoto");
            return (Criteria) this;
        }

        public Criteria andCustGenterIsNull() {
            addCriterion("cust_genter is null");
            return (Criteria) this;
        }

        public Criteria andCustGenterIsNotNull() {
            addCriterion("cust_genter is not null");
            return (Criteria) this;
        }

        public Criteria andCustGenterEqualTo(String value) {
            addCriterion("cust_genter =", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterNotEqualTo(String value) {
            addCriterion("cust_genter <>", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterGreaterThan(String value) {
            addCriterion("cust_genter >", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterGreaterThanOrEqualTo(String value) {
            addCriterion("cust_genter >=", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterLessThan(String value) {
            addCriterion("cust_genter <", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterLessThanOrEqualTo(String value) {
            addCriterion("cust_genter <=", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterLike(String value) {
            addCriterion("cust_genter like", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterNotLike(String value) {
            addCriterion("cust_genter not like", value, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterIn(List<String> values) {
            addCriterion("cust_genter in", values, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterNotIn(List<String> values) {
            addCriterion("cust_genter not in", values, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterBetween(String value1, String value2) {
            addCriterion("cust_genter between", value1, value2, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustGenterNotBetween(String value1, String value2) {
            addCriterion("cust_genter not between", value1, value2, "custGenter");
            return (Criteria) this;
        }

        public Criteria andCustProvinceIsNull() {
            addCriterion("cust_province is null");
            return (Criteria) this;
        }

        public Criteria andCustProvinceIsNotNull() {
            addCriterion("cust_province is not null");
            return (Criteria) this;
        }

        public Criteria andCustProvinceEqualTo(String value) {
            addCriterion("cust_province =", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceNotEqualTo(String value) {
            addCriterion("cust_province <>", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceGreaterThan(String value) {
            addCriterion("cust_province >", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("cust_province >=", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceLessThan(String value) {
            addCriterion("cust_province <", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceLessThanOrEqualTo(String value) {
            addCriterion("cust_province <=", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceLike(String value) {
            addCriterion("cust_province like", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceNotLike(String value) {
            addCriterion("cust_province not like", value, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceIn(List<String> values) {
            addCriterion("cust_province in", values, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceNotIn(List<String> values) {
            addCriterion("cust_province not in", values, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceBetween(String value1, String value2) {
            addCriterion("cust_province between", value1, value2, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustProvinceNotBetween(String value1, String value2) {
            addCriterion("cust_province not between", value1, value2, "custProvince");
            return (Criteria) this;
        }

        public Criteria andCustCityIsNull() {
            addCriterion("cust_city is null");
            return (Criteria) this;
        }

        public Criteria andCustCityIsNotNull() {
            addCriterion("cust_city is not null");
            return (Criteria) this;
        }

        public Criteria andCustCityEqualTo(String value) {
            addCriterion("cust_city =", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityNotEqualTo(String value) {
            addCriterion("cust_city <>", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityGreaterThan(String value) {
            addCriterion("cust_city >", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityGreaterThanOrEqualTo(String value) {
            addCriterion("cust_city >=", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityLessThan(String value) {
            addCriterion("cust_city <", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityLessThanOrEqualTo(String value) {
            addCriterion("cust_city <=", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityLike(String value) {
            addCriterion("cust_city like", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityNotLike(String value) {
            addCriterion("cust_city not like", value, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityIn(List<String> values) {
            addCriterion("cust_city in", values, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityNotIn(List<String> values) {
            addCriterion("cust_city not in", values, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityBetween(String value1, String value2) {
            addCriterion("cust_city between", value1, value2, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustCityNotBetween(String value1, String value2) {
            addCriterion("cust_city not between", value1, value2, "custCity");
            return (Criteria) this;
        }

        public Criteria andCustAreaIsNull() {
            addCriterion("cust_area is null");
            return (Criteria) this;
        }

        public Criteria andCustAreaIsNotNull() {
            addCriterion("cust_area is not null");
            return (Criteria) this;
        }

        public Criteria andCustAreaEqualTo(String value) {
            addCriterion("cust_area =", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaNotEqualTo(String value) {
            addCriterion("cust_area <>", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaGreaterThan(String value) {
            addCriterion("cust_area >", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaGreaterThanOrEqualTo(String value) {
            addCriterion("cust_area >=", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaLessThan(String value) {
            addCriterion("cust_area <", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaLessThanOrEqualTo(String value) {
            addCriterion("cust_area <=", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaLike(String value) {
            addCriterion("cust_area like", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaNotLike(String value) {
            addCriterion("cust_area not like", value, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaIn(List<String> values) {
            addCriterion("cust_area in", values, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaNotIn(List<String> values) {
            addCriterion("cust_area not in", values, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaBetween(String value1, String value2) {
            addCriterion("cust_area between", value1, value2, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustAreaNotBetween(String value1, String value2) {
            addCriterion("cust_area not between", value1, value2, "custArea");
            return (Criteria) this;
        }

        public Criteria andCustDetailIsNull() {
            addCriterion("cust_detail is null");
            return (Criteria) this;
        }

        public Criteria andCustDetailIsNotNull() {
            addCriterion("cust_detail is not null");
            return (Criteria) this;
        }

        public Criteria andCustDetailEqualTo(String value) {
            addCriterion("cust_detail =", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailNotEqualTo(String value) {
            addCriterion("cust_detail <>", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailGreaterThan(String value) {
            addCriterion("cust_detail >", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailGreaterThanOrEqualTo(String value) {
            addCriterion("cust_detail >=", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailLessThan(String value) {
            addCriterion("cust_detail <", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailLessThanOrEqualTo(String value) {
            addCriterion("cust_detail <=", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailLike(String value) {
            addCriterion("cust_detail like", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailNotLike(String value) {
            addCriterion("cust_detail not like", value, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailIn(List<String> values) {
            addCriterion("cust_detail in", values, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailNotIn(List<String> values) {
            addCriterion("cust_detail not in", values, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailBetween(String value1, String value2) {
            addCriterion("cust_detail between", value1, value2, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustDetailNotBetween(String value1, String value2) {
            addCriterion("cust_detail not between", value1, value2, "custDetail");
            return (Criteria) this;
        }

        public Criteria andCustStatusIsNull() {
            addCriterion("cust_status is null");
            return (Criteria) this;
        }

        public Criteria andCustStatusIsNotNull() {
            addCriterion("cust_status is not null");
            return (Criteria) this;
        }

        public Criteria andCustStatusEqualTo(String value) {
            addCriterion("cust_status =", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotEqualTo(String value) {
            addCriterion("cust_status <>", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusGreaterThan(String value) {
            addCriterion("cust_status >", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusGreaterThanOrEqualTo(String value) {
            addCriterion("cust_status >=", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLessThan(String value) {
            addCriterion("cust_status <", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLessThanOrEqualTo(String value) {
            addCriterion("cust_status <=", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusLike(String value) {
            addCriterion("cust_status like", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotLike(String value) {
            addCriterion("cust_status not like", value, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusIn(List<String> values) {
            addCriterion("cust_status in", values, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotIn(List<String> values) {
            addCriterion("cust_status not in", values, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusBetween(String value1, String value2) {
            addCriterion("cust_status between", value1, value2, "custStatus");
            return (Criteria) this;
        }

        public Criteria andCustStatusNotBetween(String value1, String value2) {
            addCriterion("cust_status not between", value1, value2, "custStatus");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}