package com.aistar.pojo;

import java.io.Serializable;

public class Designer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.designer_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String designerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.designer_telno
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer designerTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.designer_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String designerPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.designer_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer designerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column designer.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table designer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.designer_id
     *
     * @return the value of designer.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.designer_id
     *
     * @param designerId the value for designer.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.designer_name
     *
     * @return the value of designer.designer_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDesignerName() {
        return designerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.designer_name
     *
     * @param designerName the value for designer.designer_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerName(String designerName) {
        this.designerName = designerName == null ? null : designerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.designer_telno
     *
     * @return the value of designer.designer_telno
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDesignerTelno() {
        return designerTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.designer_telno
     *
     * @param designerTelno the value for designer.designer_telno
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerTelno(Integer designerTelno) {
        this.designerTelno = designerTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.designer_photo
     *
     * @return the value of designer.designer_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDesignerPhoto() {
        return designerPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.designer_photo
     *
     * @param designerPhoto the value for designer.designer_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerPhoto(String designerPhoto) {
        this.designerPhoto = designerPhoto == null ? null : designerPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.designer_status
     *
     * @return the value of designer.designer_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDesignerStatus() {
        return designerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.designer_status
     *
     * @param designerStatus the value for designer.designer_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerStatus(Integer designerStatus) {
        this.designerStatus = designerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.other1
     *
     * @return the value of designer.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.other1
     *
     * @param other1 the value for designer.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column designer.other2
     *
     * @return the value of designer.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column designer.other2
     *
     * @param other2 the value for designer.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table designer
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", designerId=").append(designerId);
        sb.append(", designerName=").append(designerName);
        sb.append(", designerTelno=").append(designerTelno);
        sb.append(", designerPhoto=").append(designerPhoto);
        sb.append(", designerStatus=").append(designerStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}