package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Diary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_decoration_stage
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryDecorationStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_label
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String diaryCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.compound_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String compoundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_time
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Date diaryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.enterprise_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String enterpriseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.space
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.budget
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer budget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.collect_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Long collectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.diary_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer diaryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_id
     *
     * @return the value of diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_id
     *
     * @param diaryId the value for diary.diary_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryId(Integer diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.cust_id
     *
     * @return the value of diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.cust_id
     *
     * @param custId the value for diary.cust_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_content
     *
     * @return the value of diary.diary_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryContent() {
        return diaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_content
     *
     * @param diaryContent the value for diary.diary_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryContent(String diaryContent) {
        this.diaryContent = diaryContent == null ? null : diaryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_decoration_stage
     *
     * @return the value of diary.diary_decoration_stage
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryDecorationStage() {
        return diaryDecorationStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_decoration_stage
     *
     * @param diaryDecorationStage the value for diary.diary_decoration_stage
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryDecorationStage(String diaryDecorationStage) {
        this.diaryDecorationStage = diaryDecorationStage == null ? null : diaryDecorationStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_label
     *
     * @return the value of diary.diary_label
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryLabel() {
        return diaryLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_label
     *
     * @param diaryLabel the value for diary.diary_label
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryLabel(String diaryLabel) {
        this.diaryLabel = diaryLabel == null ? null : diaryLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_province
     *
     * @return the value of diary.diary_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryProvince() {
        return diaryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_province
     *
     * @param diaryProvince the value for diary.diary_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryProvince(String diaryProvince) {
        this.diaryProvince = diaryProvince == null ? null : diaryProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_area
     *
     * @return the value of diary.diary_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryArea() {
        return diaryArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_area
     *
     * @param diaryArea the value for diary.diary_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryArea(String diaryArea) {
        this.diaryArea = diaryArea == null ? null : diaryArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_city
     *
     * @return the value of diary.diary_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDiaryCity() {
        return diaryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_city
     *
     * @param diaryCity the value for diary.diary_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryCity(String diaryCity) {
        this.diaryCity = diaryCity == null ? null : diaryCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.compound_name
     *
     * @return the value of diary.compound_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getCompoundName() {
        return compoundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.compound_name
     *
     * @param compoundName the value for diary.compound_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCompoundName(String compoundName) {
        this.compoundName = compoundName == null ? null : compoundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_time
     *
     * @return the value of diary.diary_time
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Date getDiaryTime() {
        return diaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_time
     *
     * @param diaryTime the value for diary.diary_time
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryTime(Date diaryTime) {
        this.diaryTime = diaryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.enterprise_name
     *
     * @return the value of diary.enterprise_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.enterprise_name
     *
     * @param enterpriseName the value for diary.enterprise_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.space
     *
     * @return the value of diary.space
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.space
     *
     * @param space the value for diary.space
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSpace(Integer space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.style
     *
     * @return the value of diary.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.style
     *
     * @param style the value for diary.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.budget
     *
     * @return the value of diary.budget
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.budget
     *
     * @param budget the value for diary.budget
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setBudget(Integer budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.collect_count
     *
     * @return the value of diary.collect_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Long getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.collect_count
     *
     * @param collectCount the value for diary.collect_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectCount(Long collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.diary_status
     *
     * @return the value of diary.diary_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDiaryStatus() {
        return diaryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.diary_status
     *
     * @param diaryStatus the value for diary.diary_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDiaryStatus(Integer diaryStatus) {
        this.diaryStatus = diaryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.other1
     *
     * @return the value of diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.other1
     *
     * @param other1 the value for diary.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.other2
     *
     * @return the value of diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.other2
     *
     * @param other2 the value for diary.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", diaryId=").append(diaryId);
        sb.append(", custId=").append(custId);
        sb.append(", diaryContent=").append(diaryContent);
        sb.append(", diaryDecorationStage=").append(diaryDecorationStage);
        sb.append(", diaryLabel=").append(diaryLabel);
        sb.append(", diaryProvince=").append(diaryProvince);
        sb.append(", diaryArea=").append(diaryArea);
        sb.append(", diaryCity=").append(diaryCity);
        sb.append(", compoundName=").append(compoundName);
        sb.append(", diaryTime=").append(diaryTime);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", space=").append(space);
        sb.append(", style=").append(style);
        sb.append(", budget=").append(budget);
        sb.append(", collectCount=").append(collectCount);
        sb.append(", diaryStatus=").append(diaryStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}