package com.aistar.pojo;

import java.io.Serializable;

public class Enterprise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_detail
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.attn_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String attnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.attn_tel
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Long attnTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_username
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_password
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_logo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String entLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.construction_form
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String constructionForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_type
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.minaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String minacceptPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.maxaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String maxacceptPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.service_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String serviceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.business_licence
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String businessLicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.ent_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer entStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_id
     *
     * @return the value of enterprise.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_id
     *
     * @param entId the value for enterprise.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntId(Integer entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_name
     *
     * @return the value of enterprise.ent_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntName() {
        return entName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_name
     *
     * @param entName the value for enterprise.ent_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntName(String entName) {
        this.entName = entName == null ? null : entName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_province
     *
     * @return the value of enterprise.ent_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntProvince() {
        return entProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_province
     *
     * @param entProvince the value for enterprise.ent_province
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntProvince(String entProvince) {
        this.entProvince = entProvince == null ? null : entProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_city
     *
     * @return the value of enterprise.ent_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntCity() {
        return entCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_city
     *
     * @param entCity the value for enterprise.ent_city
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntCity(String entCity) {
        this.entCity = entCity == null ? null : entCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_area
     *
     * @return the value of enterprise.ent_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntArea() {
        return entArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_area
     *
     * @param entArea the value for enterprise.ent_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntArea(String entArea) {
        this.entArea = entArea == null ? null : entArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_detail
     *
     * @return the value of enterprise.ent_detail
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntDetail() {
        return entDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_detail
     *
     * @param entDetail the value for enterprise.ent_detail
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntDetail(String entDetail) {
        this.entDetail = entDetail == null ? null : entDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.attn_name
     *
     * @return the value of enterprise.attn_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getAttnName() {
        return attnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.attn_name
     *
     * @param attnName the value for enterprise.attn_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setAttnName(String attnName) {
        this.attnName = attnName == null ? null : attnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.attn_tel
     *
     * @return the value of enterprise.attn_tel
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Long getAttnTel() {
        return attnTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.attn_tel
     *
     * @param attnTel the value for enterprise.attn_tel
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setAttnTel(Long attnTel) {
        this.attnTel = attnTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_username
     *
     * @return the value of enterprise.ent_username
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntUsername() {
        return entUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_username
     *
     * @param entUsername the value for enterprise.ent_username
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntUsername(String entUsername) {
        this.entUsername = entUsername == null ? null : entUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_password
     *
     * @return the value of enterprise.ent_password
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntPassword() {
        return entPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_password
     *
     * @param entPassword the value for enterprise.ent_password
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntPassword(String entPassword) {
        this.entPassword = entPassword == null ? null : entPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_logo
     *
     * @return the value of enterprise.ent_logo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEntLogo() {
        return entLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_logo
     *
     * @param entLogo the value for enterprise.ent_logo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntLogo(String entLogo) {
        this.entLogo = entLogo == null ? null : entLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.construction_form
     *
     * @return the value of enterprise.construction_form
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getConstructionForm() {
        return constructionForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.construction_form
     *
     * @param constructionForm the value for enterprise.construction_form
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setConstructionForm(String constructionForm) {
        this.constructionForm = constructionForm == null ? null : constructionForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_type
     *
     * @return the value of enterprise.enterprise_type
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_type
     *
     * @param enterpriseType the value for enterprise.enterprise_type
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEnterpriseType(String enterpriseType) {
        this.enterpriseType = enterpriseType == null ? null : enterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.minaccept_price
     *
     * @return the value of enterprise.minaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getMinacceptPrice() {
        return minacceptPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.minaccept_price
     *
     * @param minacceptPrice the value for enterprise.minaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setMinacceptPrice(String minacceptPrice) {
        this.minacceptPrice = minacceptPrice == null ? null : minacceptPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.maxaccept_price
     *
     * @return the value of enterprise.maxaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getMaxacceptPrice() {
        return maxacceptPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.maxaccept_price
     *
     * @param maxacceptPrice the value for enterprise.maxaccept_price
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setMaxacceptPrice(String maxacceptPrice) {
        this.maxacceptPrice = maxacceptPrice == null ? null : maxacceptPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.service_area
     *
     * @return the value of enterprise.service_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getServiceArea() {
        return serviceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.service_area
     *
     * @param serviceArea the value for enterprise.service_area
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setServiceArea(String serviceArea) {
        this.serviceArea = serviceArea == null ? null : serviceArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.business_licence
     *
     * @return the value of enterprise.business_licence
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getBusinessLicence() {
        return businessLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.business_licence
     *
     * @param businessLicence the value for enterprise.business_licence
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setBusinessLicence(String businessLicence) {
        this.businessLicence = businessLicence == null ? null : businessLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.ent_status
     *
     * @return the value of enterprise.ent_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getEntStatus() {
        return entStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.ent_status
     *
     * @param entStatus the value for enterprise.ent_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntStatus(Integer entStatus) {
        this.entStatus = entStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.other1
     *
     * @return the value of enterprise.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.other1
     *
     * @param other1 the value for enterprise.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.other2
     *
     * @return the value of enterprise.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.other2
     *
     * @param other2 the value for enterprise.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", entId=").append(entId);
        sb.append(", entName=").append(entName);
        sb.append(", entProvince=").append(entProvince);
        sb.append(", entCity=").append(entCity);
        sb.append(", entArea=").append(entArea);
        sb.append(", entDetail=").append(entDetail);
        sb.append(", attnName=").append(attnName);
        sb.append(", attnTel=").append(attnTel);
        sb.append(", entUsername=").append(entUsername);
        sb.append(", entPassword=").append(entPassword);
        sb.append(", entLogo=").append(entLogo);
        sb.append(", constructionForm=").append(constructionForm);
        sb.append(", enterpriseType=").append(enterpriseType);
        sb.append(", minacceptPrice=").append(minacceptPrice);
        sb.append(", maxacceptPrice=").append(maxacceptPrice);
        sb.append(", serviceArea=").append(serviceArea);
        sb.append(", businessLicence=").append(businessLicence);
        sb.append(", entStatus=").append(entStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}