package com.aistar.pojo;

import java.util.ArrayList;
import java.util.List;

public class EnterpriseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public EnterpriseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntIdIsNull() {
            addCriterion("ent_id is null");
            return (Criteria) this;
        }

        public Criteria andEntIdIsNotNull() {
            addCriterion("ent_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntIdEqualTo(Integer value) {
            addCriterion("ent_id =", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotEqualTo(Integer value) {
            addCriterion("ent_id <>", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThan(Integer value) {
            addCriterion("ent_id >", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ent_id >=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThan(Integer value) {
            addCriterion("ent_id <", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdLessThanOrEqualTo(Integer value) {
            addCriterion("ent_id <=", value, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdIn(List<Integer> values) {
            addCriterion("ent_id in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotIn(List<Integer> values) {
            addCriterion("ent_id not in", values, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdBetween(Integer value1, Integer value2) {
            addCriterion("ent_id between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andEntIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ent_id not between", value1, value2, "entId");
            return (Criteria) this;
        }

        public Criteria andEntNameIsNull() {
            addCriterion("ent_name is null");
            return (Criteria) this;
        }

        public Criteria andEntNameIsNotNull() {
            addCriterion("ent_name is not null");
            return (Criteria) this;
        }

        public Criteria andEntNameEqualTo(String value) {
            addCriterion("ent_name =", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotEqualTo(String value) {
            addCriterion("ent_name <>", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameGreaterThan(String value) {
            addCriterion("ent_name >", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameGreaterThanOrEqualTo(String value) {
            addCriterion("ent_name >=", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLessThan(String value) {
            addCriterion("ent_name <", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLessThanOrEqualTo(String value) {
            addCriterion("ent_name <=", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameLike(String value) {
            addCriterion("ent_name like", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotLike(String value) {
            addCriterion("ent_name not like", value, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameIn(List<String> values) {
            addCriterion("ent_name in", values, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotIn(List<String> values) {
            addCriterion("ent_name not in", values, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameBetween(String value1, String value2) {
            addCriterion("ent_name between", value1, value2, "entName");
            return (Criteria) this;
        }

        public Criteria andEntNameNotBetween(String value1, String value2) {
            addCriterion("ent_name not between", value1, value2, "entName");
            return (Criteria) this;
        }

        public Criteria andEntProvinceIsNull() {
            addCriterion("ent_province is null");
            return (Criteria) this;
        }

        public Criteria andEntProvinceIsNotNull() {
            addCriterion("ent_province is not null");
            return (Criteria) this;
        }

        public Criteria andEntProvinceEqualTo(String value) {
            addCriterion("ent_province =", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceNotEqualTo(String value) {
            addCriterion("ent_province <>", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceGreaterThan(String value) {
            addCriterion("ent_province >", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("ent_province >=", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceLessThan(String value) {
            addCriterion("ent_province <", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceLessThanOrEqualTo(String value) {
            addCriterion("ent_province <=", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceLike(String value) {
            addCriterion("ent_province like", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceNotLike(String value) {
            addCriterion("ent_province not like", value, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceIn(List<String> values) {
            addCriterion("ent_province in", values, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceNotIn(List<String> values) {
            addCriterion("ent_province not in", values, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceBetween(String value1, String value2) {
            addCriterion("ent_province between", value1, value2, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntProvinceNotBetween(String value1, String value2) {
            addCriterion("ent_province not between", value1, value2, "entProvince");
            return (Criteria) this;
        }

        public Criteria andEntCityIsNull() {
            addCriterion("ent_city is null");
            return (Criteria) this;
        }

        public Criteria andEntCityIsNotNull() {
            addCriterion("ent_city is not null");
            return (Criteria) this;
        }

        public Criteria andEntCityEqualTo(String value) {
            addCriterion("ent_city =", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityNotEqualTo(String value) {
            addCriterion("ent_city <>", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityGreaterThan(String value) {
            addCriterion("ent_city >", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityGreaterThanOrEqualTo(String value) {
            addCriterion("ent_city >=", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityLessThan(String value) {
            addCriterion("ent_city <", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityLessThanOrEqualTo(String value) {
            addCriterion("ent_city <=", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityLike(String value) {
            addCriterion("ent_city like", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityNotLike(String value) {
            addCriterion("ent_city not like", value, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityIn(List<String> values) {
            addCriterion("ent_city in", values, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityNotIn(List<String> values) {
            addCriterion("ent_city not in", values, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityBetween(String value1, String value2) {
            addCriterion("ent_city between", value1, value2, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntCityNotBetween(String value1, String value2) {
            addCriterion("ent_city not between", value1, value2, "entCity");
            return (Criteria) this;
        }

        public Criteria andEntAreaIsNull() {
            addCriterion("ent_area is null");
            return (Criteria) this;
        }

        public Criteria andEntAreaIsNotNull() {
            addCriterion("ent_area is not null");
            return (Criteria) this;
        }

        public Criteria andEntAreaEqualTo(String value) {
            addCriterion("ent_area =", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaNotEqualTo(String value) {
            addCriterion("ent_area <>", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaGreaterThan(String value) {
            addCriterion("ent_area >", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaGreaterThanOrEqualTo(String value) {
            addCriterion("ent_area >=", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaLessThan(String value) {
            addCriterion("ent_area <", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaLessThanOrEqualTo(String value) {
            addCriterion("ent_area <=", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaLike(String value) {
            addCriterion("ent_area like", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaNotLike(String value) {
            addCriterion("ent_area not like", value, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaIn(List<String> values) {
            addCriterion("ent_area in", values, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaNotIn(List<String> values) {
            addCriterion("ent_area not in", values, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaBetween(String value1, String value2) {
            addCriterion("ent_area between", value1, value2, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntAreaNotBetween(String value1, String value2) {
            addCriterion("ent_area not between", value1, value2, "entArea");
            return (Criteria) this;
        }

        public Criteria andEntDetailIsNull() {
            addCriterion("ent_detail is null");
            return (Criteria) this;
        }

        public Criteria andEntDetailIsNotNull() {
            addCriterion("ent_detail is not null");
            return (Criteria) this;
        }

        public Criteria andEntDetailEqualTo(String value) {
            addCriterion("ent_detail =", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailNotEqualTo(String value) {
            addCriterion("ent_detail <>", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailGreaterThan(String value) {
            addCriterion("ent_detail >", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailGreaterThanOrEqualTo(String value) {
            addCriterion("ent_detail >=", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailLessThan(String value) {
            addCriterion("ent_detail <", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailLessThanOrEqualTo(String value) {
            addCriterion("ent_detail <=", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailLike(String value) {
            addCriterion("ent_detail like", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailNotLike(String value) {
            addCriterion("ent_detail not like", value, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailIn(List<String> values) {
            addCriterion("ent_detail in", values, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailNotIn(List<String> values) {
            addCriterion("ent_detail not in", values, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailBetween(String value1, String value2) {
            addCriterion("ent_detail between", value1, value2, "entDetail");
            return (Criteria) this;
        }

        public Criteria andEntDetailNotBetween(String value1, String value2) {
            addCriterion("ent_detail not between", value1, value2, "entDetail");
            return (Criteria) this;
        }

        public Criteria andAttnNameIsNull() {
            addCriterion("attn_name is null");
            return (Criteria) this;
        }

        public Criteria andAttnNameIsNotNull() {
            addCriterion("attn_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttnNameEqualTo(String value) {
            addCriterion("attn_name =", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameNotEqualTo(String value) {
            addCriterion("attn_name <>", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameGreaterThan(String value) {
            addCriterion("attn_name >", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameGreaterThanOrEqualTo(String value) {
            addCriterion("attn_name >=", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameLessThan(String value) {
            addCriterion("attn_name <", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameLessThanOrEqualTo(String value) {
            addCriterion("attn_name <=", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameLike(String value) {
            addCriterion("attn_name like", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameNotLike(String value) {
            addCriterion("attn_name not like", value, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameIn(List<String> values) {
            addCriterion("attn_name in", values, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameNotIn(List<String> values) {
            addCriterion("attn_name not in", values, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameBetween(String value1, String value2) {
            addCriterion("attn_name between", value1, value2, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnNameNotBetween(String value1, String value2) {
            addCriterion("attn_name not between", value1, value2, "attnName");
            return (Criteria) this;
        }

        public Criteria andAttnTelIsNull() {
            addCriterion("attn_tel is null");
            return (Criteria) this;
        }

        public Criteria andAttnTelIsNotNull() {
            addCriterion("attn_tel is not null");
            return (Criteria) this;
        }

        public Criteria andAttnTelEqualTo(Long value) {
            addCriterion("attn_tel =", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelNotEqualTo(Long value) {
            addCriterion("attn_tel <>", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelGreaterThan(Long value) {
            addCriterion("attn_tel >", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelGreaterThanOrEqualTo(Long value) {
            addCriterion("attn_tel >=", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelLessThan(Long value) {
            addCriterion("attn_tel <", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelLessThanOrEqualTo(Long value) {
            addCriterion("attn_tel <=", value, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelIn(List<Long> values) {
            addCriterion("attn_tel in", values, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelNotIn(List<Long> values) {
            addCriterion("attn_tel not in", values, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelBetween(Long value1, Long value2) {
            addCriterion("attn_tel between", value1, value2, "attnTel");
            return (Criteria) this;
        }

        public Criteria andAttnTelNotBetween(Long value1, Long value2) {
            addCriterion("attn_tel not between", value1, value2, "attnTel");
            return (Criteria) this;
        }

        public Criteria andEntUsernameIsNull() {
            addCriterion("ent_username is null");
            return (Criteria) this;
        }

        public Criteria andEntUsernameIsNotNull() {
            addCriterion("ent_username is not null");
            return (Criteria) this;
        }

        public Criteria andEntUsernameEqualTo(String value) {
            addCriterion("ent_username =", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameNotEqualTo(String value) {
            addCriterion("ent_username <>", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameGreaterThan(String value) {
            addCriterion("ent_username >", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("ent_username >=", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameLessThan(String value) {
            addCriterion("ent_username <", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameLessThanOrEqualTo(String value) {
            addCriterion("ent_username <=", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameLike(String value) {
            addCriterion("ent_username like", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameNotLike(String value) {
            addCriterion("ent_username not like", value, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameIn(List<String> values) {
            addCriterion("ent_username in", values, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameNotIn(List<String> values) {
            addCriterion("ent_username not in", values, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameBetween(String value1, String value2) {
            addCriterion("ent_username between", value1, value2, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntUsernameNotBetween(String value1, String value2) {
            addCriterion("ent_username not between", value1, value2, "entUsername");
            return (Criteria) this;
        }

        public Criteria andEntPasswordIsNull() {
            addCriterion("ent_password is null");
            return (Criteria) this;
        }

        public Criteria andEntPasswordIsNotNull() {
            addCriterion("ent_password is not null");
            return (Criteria) this;
        }

        public Criteria andEntPasswordEqualTo(String value) {
            addCriterion("ent_password =", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordNotEqualTo(String value) {
            addCriterion("ent_password <>", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordGreaterThan(String value) {
            addCriterion("ent_password >", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("ent_password >=", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordLessThan(String value) {
            addCriterion("ent_password <", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordLessThanOrEqualTo(String value) {
            addCriterion("ent_password <=", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordLike(String value) {
            addCriterion("ent_password like", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordNotLike(String value) {
            addCriterion("ent_password not like", value, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordIn(List<String> values) {
            addCriterion("ent_password in", values, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordNotIn(List<String> values) {
            addCriterion("ent_password not in", values, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordBetween(String value1, String value2) {
            addCriterion("ent_password between", value1, value2, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntPasswordNotBetween(String value1, String value2) {
            addCriterion("ent_password not between", value1, value2, "entPassword");
            return (Criteria) this;
        }

        public Criteria andEntLogoIsNull() {
            addCriterion("ent_logo is null");
            return (Criteria) this;
        }

        public Criteria andEntLogoIsNotNull() {
            addCriterion("ent_logo is not null");
            return (Criteria) this;
        }

        public Criteria andEntLogoEqualTo(String value) {
            addCriterion("ent_logo =", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoNotEqualTo(String value) {
            addCriterion("ent_logo <>", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoGreaterThan(String value) {
            addCriterion("ent_logo >", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoGreaterThanOrEqualTo(String value) {
            addCriterion("ent_logo >=", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoLessThan(String value) {
            addCriterion("ent_logo <", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoLessThanOrEqualTo(String value) {
            addCriterion("ent_logo <=", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoLike(String value) {
            addCriterion("ent_logo like", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoNotLike(String value) {
            addCriterion("ent_logo not like", value, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoIn(List<String> values) {
            addCriterion("ent_logo in", values, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoNotIn(List<String> values) {
            addCriterion("ent_logo not in", values, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoBetween(String value1, String value2) {
            addCriterion("ent_logo between", value1, value2, "entLogo");
            return (Criteria) this;
        }

        public Criteria andEntLogoNotBetween(String value1, String value2) {
            addCriterion("ent_logo not between", value1, value2, "entLogo");
            return (Criteria) this;
        }

        public Criteria andConstructionFormIsNull() {
            addCriterion("construction_form is null");
            return (Criteria) this;
        }

        public Criteria andConstructionFormIsNotNull() {
            addCriterion("construction_form is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionFormEqualTo(String value) {
            addCriterion("construction_form =", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormNotEqualTo(String value) {
            addCriterion("construction_form <>", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormGreaterThan(String value) {
            addCriterion("construction_form >", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormGreaterThanOrEqualTo(String value) {
            addCriterion("construction_form >=", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormLessThan(String value) {
            addCriterion("construction_form <", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormLessThanOrEqualTo(String value) {
            addCriterion("construction_form <=", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormLike(String value) {
            addCriterion("construction_form like", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormNotLike(String value) {
            addCriterion("construction_form not like", value, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormIn(List<String> values) {
            addCriterion("construction_form in", values, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormNotIn(List<String> values) {
            addCriterion("construction_form not in", values, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormBetween(String value1, String value2) {
            addCriterion("construction_form between", value1, value2, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andConstructionFormNotBetween(String value1, String value2) {
            addCriterion("construction_form not between", value1, value2, "constructionForm");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeIsNull() {
            addCriterion("enterprise_type is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeIsNotNull() {
            addCriterion("enterprise_type is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeEqualTo(String value) {
            addCriterion("enterprise_type =", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeNotEqualTo(String value) {
            addCriterion("enterprise_type <>", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeGreaterThan(String value) {
            addCriterion("enterprise_type >", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("enterprise_type >=", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeLessThan(String value) {
            addCriterion("enterprise_type <", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeLessThanOrEqualTo(String value) {
            addCriterion("enterprise_type <=", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeLike(String value) {
            addCriterion("enterprise_type like", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeNotLike(String value) {
            addCriterion("enterprise_type not like", value, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeIn(List<String> values) {
            addCriterion("enterprise_type in", values, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeNotIn(List<String> values) {
            addCriterion("enterprise_type not in", values, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeBetween(String value1, String value2) {
            addCriterion("enterprise_type between", value1, value2, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andEnterpriseTypeNotBetween(String value1, String value2) {
            addCriterion("enterprise_type not between", value1, value2, "enterpriseType");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceIsNull() {
            addCriterion("minaccept_price is null");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceIsNotNull() {
            addCriterion("minaccept_price is not null");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceEqualTo(String value) {
            addCriterion("minaccept_price =", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceNotEqualTo(String value) {
            addCriterion("minaccept_price <>", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceGreaterThan(String value) {
            addCriterion("minaccept_price >", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceGreaterThanOrEqualTo(String value) {
            addCriterion("minaccept_price >=", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceLessThan(String value) {
            addCriterion("minaccept_price <", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceLessThanOrEqualTo(String value) {
            addCriterion("minaccept_price <=", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceLike(String value) {
            addCriterion("minaccept_price like", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceNotLike(String value) {
            addCriterion("minaccept_price not like", value, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceIn(List<String> values) {
            addCriterion("minaccept_price in", values, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceNotIn(List<String> values) {
            addCriterion("minaccept_price not in", values, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceBetween(String value1, String value2) {
            addCriterion("minaccept_price between", value1, value2, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMinacceptPriceNotBetween(String value1, String value2) {
            addCriterion("minaccept_price not between", value1, value2, "minacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceIsNull() {
            addCriterion("maxaccept_price is null");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceIsNotNull() {
            addCriterion("maxaccept_price is not null");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceEqualTo(String value) {
            addCriterion("maxaccept_price =", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceNotEqualTo(String value) {
            addCriterion("maxaccept_price <>", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceGreaterThan(String value) {
            addCriterion("maxaccept_price >", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceGreaterThanOrEqualTo(String value) {
            addCriterion("maxaccept_price >=", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceLessThan(String value) {
            addCriterion("maxaccept_price <", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceLessThanOrEqualTo(String value) {
            addCriterion("maxaccept_price <=", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceLike(String value) {
            addCriterion("maxaccept_price like", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceNotLike(String value) {
            addCriterion("maxaccept_price not like", value, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceIn(List<String> values) {
            addCriterion("maxaccept_price in", values, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceNotIn(List<String> values) {
            addCriterion("maxaccept_price not in", values, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceBetween(String value1, String value2) {
            addCriterion("maxaccept_price between", value1, value2, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andMaxacceptPriceNotBetween(String value1, String value2) {
            addCriterion("maxaccept_price not between", value1, value2, "maxacceptPrice");
            return (Criteria) this;
        }

        public Criteria andServiceAreaIsNull() {
            addCriterion("service_area is null");
            return (Criteria) this;
        }

        public Criteria andServiceAreaIsNotNull() {
            addCriterion("service_area is not null");
            return (Criteria) this;
        }

        public Criteria andServiceAreaEqualTo(String value) {
            addCriterion("service_area =", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaNotEqualTo(String value) {
            addCriterion("service_area <>", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaGreaterThan(String value) {
            addCriterion("service_area >", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaGreaterThanOrEqualTo(String value) {
            addCriterion("service_area >=", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaLessThan(String value) {
            addCriterion("service_area <", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaLessThanOrEqualTo(String value) {
            addCriterion("service_area <=", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaLike(String value) {
            addCriterion("service_area like", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaNotLike(String value) {
            addCriterion("service_area not like", value, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaIn(List<String> values) {
            addCriterion("service_area in", values, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaNotIn(List<String> values) {
            addCriterion("service_area not in", values, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaBetween(String value1, String value2) {
            addCriterion("service_area between", value1, value2, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andServiceAreaNotBetween(String value1, String value2) {
            addCriterion("service_area not between", value1, value2, "serviceArea");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceIsNull() {
            addCriterion("business_licence is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceIsNotNull() {
            addCriterion("business_licence is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceEqualTo(String value) {
            addCriterion("business_licence =", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceNotEqualTo(String value) {
            addCriterion("business_licence <>", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceGreaterThan(String value) {
            addCriterion("business_licence >", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceGreaterThanOrEqualTo(String value) {
            addCriterion("business_licence >=", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceLessThan(String value) {
            addCriterion("business_licence <", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceLessThanOrEqualTo(String value) {
            addCriterion("business_licence <=", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceLike(String value) {
            addCriterion("business_licence like", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceNotLike(String value) {
            addCriterion("business_licence not like", value, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceIn(List<String> values) {
            addCriterion("business_licence in", values, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceNotIn(List<String> values) {
            addCriterion("business_licence not in", values, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceBetween(String value1, String value2) {
            addCriterion("business_licence between", value1, value2, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenceNotBetween(String value1, String value2) {
            addCriterion("business_licence not between", value1, value2, "businessLicence");
            return (Criteria) this;
        }

        public Criteria andEntStatusIsNull() {
            addCriterion("ent_status is null");
            return (Criteria) this;
        }

        public Criteria andEntStatusIsNotNull() {
            addCriterion("ent_status is not null");
            return (Criteria) this;
        }

        public Criteria andEntStatusEqualTo(Integer value) {
            addCriterion("ent_status =", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusNotEqualTo(Integer value) {
            addCriterion("ent_status <>", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusGreaterThan(Integer value) {
            addCriterion("ent_status >", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ent_status >=", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusLessThan(Integer value) {
            addCriterion("ent_status <", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ent_status <=", value, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusIn(List<Integer> values) {
            addCriterion("ent_status in", values, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusNotIn(List<Integer> values) {
            addCriterion("ent_status not in", values, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusBetween(Integer value1, Integer value2) {
            addCriterion("ent_status between", value1, value2, "entStatus");
            return (Criteria) this;
        }

        public Criteria andEntStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ent_status not between", value1, value2, "entStatus");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}