package com.aistar.pojo;

import java.io.Serializable;

public class Programme implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer programmeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String programmeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.pic_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer designerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.cform
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer cform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_decoration_duration
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String programmeDecorationDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_size
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer programmeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Double programmeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.collection_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Long collectionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.programme_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer programmeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column programme.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table programme
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_id
     *
     * @return the value of programme.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getProgrammeId() {
        return programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_id
     *
     * @param programmeId the value for programme.programme_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeId(Integer programmeId) {
        this.programmeId = programmeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_name
     *
     * @return the value of programme.programme_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getProgrammeName() {
        return programmeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_name
     *
     * @param programmeName the value for programme.programme_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeName(String programmeName) {
        this.programmeName = programmeName == null ? null : programmeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.ent_id
     *
     * @return the value of programme.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.ent_id
     *
     * @param entId the value for programme.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntId(Integer entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.pic_id
     *
     * @return the value of programme.pic_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.pic_id
     *
     * @param picId the value for programme.pic_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.designer_id
     *
     * @return the value of programme.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getDesignerId() {
        return designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.designer_id
     *
     * @param designerId the value for programme.designer_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDesignerId(Integer designerId) {
        this.designerId = designerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.cform
     *
     * @return the value of programme.cform
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getCform() {
        return cform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.cform
     *
     * @param cform the value for programme.cform
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCform(Integer cform) {
        this.cform = cform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_decoration_duration
     *
     * @return the value of programme.programme_decoration_duration
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getProgrammeDecorationDuration() {
        return programmeDecorationDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_decoration_duration
     *
     * @param programmeDecorationDuration the value for programme.programme_decoration_duration
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeDecorationDuration(String programmeDecorationDuration) {
        this.programmeDecorationDuration = programmeDecorationDuration == null ? null : programmeDecorationDuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_size
     *
     * @return the value of programme.programme_size
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getProgrammeSize() {
        return programmeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_size
     *
     * @param programmeSize the value for programme.programme_size
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeSize(Integer programmeSize) {
        this.programmeSize = programmeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.style
     *
     * @return the value of programme.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.style
     *
     * @param style the value for programme.style
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_cost
     *
     * @return the value of programme.programme_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Double getProgrammeCost() {
        return programmeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_cost
     *
     * @param programmeCost the value for programme.programme_cost
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeCost(Double programmeCost) {
        this.programmeCost = programmeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.collection_count
     *
     * @return the value of programme.collection_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Long getCollectionCount() {
        return collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.collection_count
     *
     * @param collectionCount the value for programme.collection_count
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setCollectionCount(Long collectionCount) {
        this.collectionCount = collectionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.programme_status
     *
     * @return the value of programme.programme_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getProgrammeStatus() {
        return programmeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.programme_status
     *
     * @param programmeStatus the value for programme.programme_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setProgrammeStatus(Integer programmeStatus) {
        this.programmeStatus = programmeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.other1
     *
     * @return the value of programme.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.other1
     *
     * @param other1 the value for programme.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column programme.other2
     *
     * @return the value of programme.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column programme.other2
     *
     * @param other2 the value for programme.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programme
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", programmeId=").append(programmeId);
        sb.append(", programmeName=").append(programmeName);
        sb.append(", entId=").append(entId);
        sb.append(", picId=").append(picId);
        sb.append(", designerId=").append(designerId);
        sb.append(", cform=").append(cform);
        sb.append(", programmeDecorationDuration=").append(programmeDecorationDuration);
        sb.append(", programmeSize=").append(programmeSize);
        sb.append(", style=").append(style);
        sb.append(", programmeCost=").append(programmeCost);
        sb.append(", collectionCount=").append(collectionCount);
        sb.append(", programmeStatus=").append(programmeStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}