package com.aistar.pojo;

import java.io.Serializable;

public class Qualification implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.q_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer qId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer entId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.medal_pictures
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String medalPictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.description
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.q_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer qStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qualification.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qualification
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.q_id
     *
     * @return the value of qualification.q_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.q_id
     *
     * @param qId the value for qualification.q_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.ent_id
     *
     * @return the value of qualification.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getEntId() {
        return entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.ent_id
     *
     * @param entId the value for qualification.ent_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setEntId(Integer entId) {
        this.entId = entId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.medal_pictures
     *
     * @return the value of qualification.medal_pictures
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getMedalPictures() {
        return medalPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.medal_pictures
     *
     * @param medalPictures the value for qualification.medal_pictures
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setMedalPictures(String medalPictures) {
        this.medalPictures = medalPictures == null ? null : medalPictures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.description
     *
     * @return the value of qualification.description
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.description
     *
     * @param description the value for qualification.description
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.q_status
     *
     * @return the value of qualification.q_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getqStatus() {
        return qStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.q_status
     *
     * @param qStatus the value for qualification.q_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setqStatus(Integer qStatus) {
        this.qStatus = qStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.other1
     *
     * @return the value of qualification.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.other1
     *
     * @param other1 the value for qualification.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qualification.other2
     *
     * @return the value of qualification.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qualification.other2
     *
     * @param other2 the value for qualification.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qualification
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qId=").append(qId);
        sb.append(", entId=").append(entId);
        sb.append(", medalPictures=").append(medalPictures);
        sb.append(", description=").append(description);
        sb.append(", qStatus=").append(qStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}