package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class SystemMessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.sm_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer smId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.sm_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String smName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.sm_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String smContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.sm_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Date smDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.sm_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private Integer smStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_message.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.sm_id
     *
     * @return the value of system_message.sm_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getSmId() {
        return smId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.sm_id
     *
     * @param smId the value for system_message.sm_id
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSmId(Integer smId) {
        this.smId = smId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.sm_name
     *
     * @return the value of system_message.sm_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getSmName() {
        return smName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.sm_name
     *
     * @param smName the value for system_message.sm_name
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSmName(String smName) {
        this.smName = smName == null ? null : smName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.sm_content
     *
     * @return the value of system_message.sm_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getSmContent() {
        return smContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.sm_content
     *
     * @param smContent the value for system_message.sm_content
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSmContent(String smContent) {
        this.smContent = smContent == null ? null : smContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.sm_date
     *
     * @return the value of system_message.sm_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Date getSmDate() {
        return smDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.sm_date
     *
     * @param smDate the value for system_message.sm_date
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSmDate(Date smDate) {
        this.smDate = smDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.sm_status
     *
     * @return the value of system_message.sm_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public Integer getSmStatus() {
        return smStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.sm_status
     *
     * @param smStatus the value for system_message.sm_status
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setSmStatus(Integer smStatus) {
        this.smStatus = smStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.other1
     *
     * @return the value of system_message.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.other1
     *
     * @param other1 the value for system_message.other1
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_message.other2
     *
     * @return the value of system_message.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_message.other2
     *
     * @param other2 the value for system_message.other2
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", smId=").append(smId);
        sb.append(", smName=").append(smName);
        sb.append(", smContent=").append(smContent);
        sb.append(", smDate=").append(smDate);
        sb.append(", smStatus=").append(smStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}