package com.aistar.mapper;

import com.aistar.pojo.Booking;
import com.aistar.pojo.BookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<Booking> selectByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    Booking selectByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table booking
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(Booking record);
}