package com.aistar.mapper;

import com.aistar.pojo.Calculator;
import com.aistar.pojo.CalculatorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CalculatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(CalculatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(CalculatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer calculatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(Calculator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(Calculator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<Calculator> selectByExample(CalculatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    Calculator selectByPrimaryKey(Integer calculatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Calculator record, @Param("example") CalculatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") Calculator record, @Param("example") CalculatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(Calculator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calculator
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(Calculator record);
}