package com.aistar.mapper;

import com.aistar.pojo.Collections;
import com.aistar.pojo.CollectionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CollectionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(CollectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(CollectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(Collections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(Collections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<Collections> selectByExample(CollectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    Collections selectByPrimaryKey(Integer collectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Collections record, @Param("example") CollectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") Collections record, @Param("example") CollectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(Collections record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(Collections record);
}