package com.aistar.mapper;

import com.aistar.pojo.CollectionsDiary;
import com.aistar.pojo.CollectionsDiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CollectionsDiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(CollectionsDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(CollectionsDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer collectionDiaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(CollectionsDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(CollectionsDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<CollectionsDiary> selectByExample(CollectionsDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    CollectionsDiary selectByPrimaryKey(Integer collectionDiaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") CollectionsDiary record, @Param("example") CollectionsDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") CollectionsDiary record, @Param("example") CollectionsDiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(CollectionsDiary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collections_diary
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(CollectionsDiary record);
}