package com.aistar.mapper;

import com.aistar.pojo.DecorationProgress;
import com.aistar.pojo.DecorationProgressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DecorationProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(DecorationProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(DecorationProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer decorationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(DecorationProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(DecorationProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<DecorationProgress> selectByExample(DecorationProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    DecorationProgress selectByPrimaryKey(Integer decorationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") DecorationProgress record, @Param("example") DecorationProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") DecorationProgress record, @Param("example") DecorationProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(DecorationProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_progress
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(DecorationProgress record);
}