package com.aistar.mapper;

import com.aistar.pojo.DiaryPhoto;
import com.aistar.pojo.DiaryPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DiaryPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(DiaryPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(DiaryPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(DiaryPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(DiaryPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<DiaryPhoto> selectByExample(DiaryPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    DiaryPhoto selectByPrimaryKey(Integer photoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") DiaryPhoto record, @Param("example") DiaryPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") DiaryPhoto record, @Param("example") DiaryPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(DiaryPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_photo
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(DiaryPhoto record);
}