package com.aistar.mapper;

import com.aistar.pojo.SystemMessage;
import com.aistar.pojo.SystemMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(SystemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(SystemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer smId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<SystemMessage> selectByExample(SystemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    SystemMessage selectByPrimaryKey(Integer smId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") SystemMessage record, @Param("example") SystemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") SystemMessage record, @Param("example") SystemMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(SystemMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_message
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(SystemMessage record);
}