package com.aistar.mapper;

import com.aistar.pojo.WorkPicture;
import com.aistar.pojo.WorkPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface WorkPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int countByExample(WorkPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByExample(WorkPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int deleteByPrimaryKey(Integer wpicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insert(WorkPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int insertSelective(WorkPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    List<WorkPicture> selectByExample(WorkPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    WorkPicture selectByPrimaryKey(Integer wpicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") WorkPicture record, @Param("example") WorkPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByExample(@Param("record") WorkPicture record, @Param("example") WorkPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKeySelective(WorkPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_picture
     *
     * @mbggenerated Sat Sep 28 16:46:13 CST 2019
     */
    int updateByPrimaryKey(WorkPicture record);
}